name: trex
description: The trex game made with flame!

version: 2.0.0

environment:
  sdk: '^3.3.0-279.3.beta'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/sprite.png
    - assets/images/trex.png

